### ISSUE TITLE
Getting run time error: RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by abhimishra91** [devkosal/tutorials#1]
Hi, Thanks for your post. But when i am trying this notebook, i am getting a run time error. 
The difference in my data-set being that its a multi-class classification rather than a binary. 

Traceback: 

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-26-be1af66bc83f> in <module>()
      1 learn.model.roberta.train() # setting roberta to train as it is in eval mode by default
----> 2 learn.fit_one_cycle(config.epochs, max_lr=config.max_lr)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/train.py in fit_one_cycle(learn, cyc_len, max_lr, moms, div_factor, pct_start, final_div, wd, callbacks, tot_epochs, start_epoch)
     20     callbacks.append(OneCycleScheduler(learn, max_lr, moms=moms, div_factor=div_factor, pct_start=pct_start,
     21                                        final_div=final_div, tot_epochs=tot_epochs, start_epoch=start_epoch))
---> 22     learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
     23 
     24 def lr_find(learn:Learner, start_lr:Floats=1e-7, end_lr:Floats=10, num_it:int=100, stop_div:bool=True, wd:float=None):

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/basic_train.py in fit(self, epochs, lr, wd, callbacks)
    198         callbacks = [cb(self) for cb in self.callback_fns + listify(defaults.extra_callback_fns)] + listify(callbacks)
    199         if defaults.extra_callbacks is not None: callbacks += defaults.extra_callbacks
--> 200         fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
    201 
    202     def create_opt(self, lr:Floats, wd:Floats=0.)->None:

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/basic_train.py in fit(epochs, learn, callbacks, metrics)
     97             cb_handler.set_dl(learn.data.train_dl)
     98             cb_handler.on_epoch_begin()
---> 99             for xb,yb in progress_bar(learn.data.train_dl, parent=pbar):
    100                 xb, yb = cb_handler.on_batch_begin(xb, yb)
    101                 loss = loss_batch(learn.model, xb, yb, learn.loss_func, learn.opt, cb_handler)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastprogress/fastprogress.py in __iter__(self)
     70         self.update(0)
     71         try:
---> 72             for i,o in enumerate(self._gen):
     73                 if i >= self.total: break
     74                 yield o

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai/basic_data.py in __iter__(self)
     73     def __iter__(self):
     74         "Process and returns items from `DataLoader`."
---> 75         for b in self.dl: yield self.proc_batch(b)
     76 
     77     @classmethod

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    580                 self.reorder_dict[idx] = batch
    581                 continue
--> 582             return self._process_next_batch(batch)
    583 
    584     next = __next__  # Python 2 compatibility

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    606                 raise Exception("KeyError:" + batch.exc_msg)
    607             else:
--> 608                 raise batch.exc_type(batch.exc_msg)
    609         return batch
    610 

RuntimeError: Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 41, in _pin_memory_loop
    batch = pin_memory_batch(batch)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 58, in pin_memory_batch
    return [pin_memory_batch(sample) for sample in batch]
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 58, in <listcomp>
    return [pin_memory_batch(sample) for sample in batch]
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 50, in pin_memory_batch
    return batch.pin_memory()
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THC/THCCachingHostAllocator.cpp:265


```

**Comment by devkosal** [comment]
Hi, 

Have you updated 'num_labels' variable in the config? You should change '2' to the number of possible classes in your dataset.

**Comment by abhimishra91** [comment]
> Hi,
> 
> Have you updated 'num_labels' variable in the config? You should change '2' to the number of possible classes in your dataset.

Hey, yes i have already done that. Still getting the same error.

**Comment by devkosal** [comment]
> > Hi,
> > Have you updated 'num_labels' variable in the config? You should change '2' to the number of possible classes in your dataset.
> 
> Hey, yes i have already done that. Still getting the same error.

I see. Is it possible for you to share your dataset and/or code with me? You can email it to me. I will try to replicate the issue. I have also just uploaded a tutorial for the SuperGLUE task CB which involves more than 2 labels (as well as multiple sequences/feat_cols which may not be relevant to your needs). It can be found [here](https://nbviewer.jupyter.org/github/devkosal/tutorials/blob/master/fastai_roberta_superglue/RoBERTa%20with%20Fastai%20-%20CB.ipynb)

**Comment by devkosal** [comment]
> > Hi,
> > Have you updated 'num_labels' variable in the config? You should change '2' to the number of possible classes in your dataset.
> 
> Hey, yes i have already done that. Still getting the same error.

Ah I believe I found the issue. In the line where CustomRobertaModel is initialized, please specify num_labels. E.g. roberta_model = CustomRobertaModel(num_labels = config.num_labels)

Edit: repo updated

**Comment by abhimishra91** [comment]
> > > Hi,
> > > Have you updated 'num_labels' variable in the config? You should change '2' to the number of possible classes in your dataset.
> > 
> > 
> > Hey, yes i have already done that. Still getting the same error.
> 
> Ah I believe I found the issue. In the line where CustomRobertaModel is initialized, please specify num_labels. E.g. roberta_model = CustomRobertaModel(num_labels = config.num_labels)
> 
> Edit: repo updated

Hey, @devkosal this worked. Thank you for that! I will close out this issue.
